title: Eggsample Status
buildFuture: true
defaultContentLanguage: en
languageCode: en
baseURL: https://elaborate-stroopwafel-8cbc42.netlify.app
theme: cstate
preserveTaxonomyNames: true
taxonomies:
  affected: affected
outputs:
  page:
    - html
    - json
  section:
    - html
    - json
    - rss
  home:
    - html
    - json
    - rss
    - svg
  term:
    - html
    - json
    - rss
    - svg
outputFormats:
  svg:
    isPlainText: true
    mediaType: image/svg+xml
enableGitInfo: true
params:
  skipSeconds: false
  useRelativeTime: true
  disableDarkMode: false
  shortDateFormat: 15:04 UTC — Jan 2
  down: "#e60000"
  systems:
    - name: Gateway
      category: Lavalink Status
    - name: Backup Gateway
      category: Lavalink Status
    - name: Website
      description: The web frontend for the application.
      category: Lavalink Status
      link: https://example.com/
    - name: API
      description: The guts of the application.
      category: Lavalink Status
    - name: Media Proxy
      description: This is the service responsible for serving images, audio, and
        video. It is reliant on our CDN.
      category: Lavalink Status
  dateFormat: January 2, 2006 at 3:04 PM UTC
  brand: "#0a0c0f"
  enableLastMod: true
  headerTextColor: white
  logo: https://github.com/cstate/cstate/raw/master/images/cstate-logo-bg.svg?sanitize=true
  incidentPostsPerPage: 10
  googleAnalytics: UA-00000000-1
  alwaysKeepBrandColor: true
  disableComplexCalculations: false
  useLogo: true
  disrupted: "#cc4400"
  notice: "#24478f"
  incidentHistoryFormat: yearly
  disableIncidentHistory: false
  ok: "#008000"
  categories:
    - name: Lavalink Status
      description: The main servers are located here.
      closed: false
    - name: Uncategorized
      untitled: true
  description: We continuously monitor the status of our services and if there are
    any interruptions, a note will be posted here.
  enableCustomHTML: true
  useLargeHeaderDesign: false
